server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
        partitioned: true

spring:
  application:
    name: protin_cal
  datasource:
    url: jdbc:mysql://test-db.cvymy48u495a.ap-northeast-2.rds.amazonaws.com/workout?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: takch02
    password: tagtag1010
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
